services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: oficina-api
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:8080
      ConnectionStrings__DefaultConnection: Host=db;Port=5432;Database=oficina;Username=postgres;Password=postgres
      Jwt__Key: trocar-esta-chave-em-producao-com-no-minimo-32-caracteres
      Jwt__Issuer: OficinaMecanica
      Jwt__Audience: OficinaMecanica.Admin
      Jwt__AdminUser: admin
      Jwt__AdminPassword: Admin@123
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:16-alpine
    container_name: oficina-postgres
    environment:
      POSTGRES_DB: oficina
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - oficina_pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d oficina"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  oficina_pgdata:
