apiVersion: v1
kind: ConfigMap
metadata:
  name: oficina-config
  namespace: oficina
data:
  ASPNETCORE_ENVIRONMENT: "Development"
  ASPNETCORE_URLS: "http://+:8080"
  Jwt__Issuer: "OficinaMecanica"
  Jwt__Audience: "OficinaMecanica.Admin"
  Jwt__AdminUser: "admin"
  POSTGRES_DB: "oficina"