# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net
name: CI - Build and Tests

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"

      - name: Restore
        run: dotnet restore OficinaMecanica.sln

      - name: Build
        run: dotnet build OficinaMecanica.sln --configuration Release --no-restore

      - name: Test
        run: dotnet test Oficina.Tests/Oficina.Tests.csproj --configuration Release --no-build --verbosity normal
