name: CI - Build and Tests

on:
  push:
    branches: [ "develop", "master" ]
  pull_request:
    branches: [ "develop", "master" ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build-test:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"

      - name: Restore
        run: dotnet restore OficinaMecanica.sln

      - name: Build
        run: dotnet build OficinaMecanica.sln --configuration Release --no-restore

      - name: Test
        run: dotnet test Oficina.Tests/Oficina.Tests.csproj --configuration Release --no-build --verbosity normal
