name: Kubernetes Manifests

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  validate-k8s:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup kubeconform
        uses: yokawasa/action-setup-kube-tools@v0.11.2
        with:
          kubeconform: '0.6.7'

      - name: Show repository files
        run: |
          pwd
          ls -la
          ls -la k8s

      - name: Validate Kubernetes manifests
        run: |
          kubeconform -strict -summary \
            k8s/namespace.yaml \
            k8s/configmap.yaml \
            k8s/secret.yaml \
            k8s/postgres-deployment.yaml \
            k8s/postgres-service.yaml \
            k8s/api-deployment.yaml \
            k8s/api-service.yaml \
            k8s/hpa.yaml
